export const data = [
  {
    id: "nor",
    country: "Norrbotten",
    regions: [
      { id: "nor_arj", region: "Arjeplog", regionId: "nor" },
      { id: "nor_arv", region: "Arvidsjaur", regionId: "nor" },
      { id: "nor_bod", region: "Boden", regionId: "nor" },
      { id: "nor_gal", region: "Gällivare", regionId: "nor" },
      { id: "nor_hap", region: "Haparanda", regionId: "nor" },
      { id: "nor_jok", region: "Jokkmokk", regionId: "nor" },
      { id: "nor_kal", region: "Kalix", regionId: "nor" },
      { id: "nor_kir", region: "Kiruna", regionId: "nor" },
      { id: "nor_lul", region: "Luleå", regionId: "nor" },
      { id: "nor_paj", region: "Pajala", regionId: "nor" },
      { id: "nor_pit", region: "Piteå", regionId: "nor" },
      { id: "nor_alv", region: "Älvsbyn", regionId: "nor" },
      { id: "nor_kve", region: "Överkalix", regionId: "nor" },
      { id: "nor_tve", region: "Övertorneå", regionId: "nor" },
    ],
  },
  {
    id: "ble",
    country: "Blekinge",
    regions: [
      { id: "ble_har", region: "Karlshamn", regionId: "ble" },
      { id: "ble_rar", region: "Karlskrona", regionId: "ble" },
      { id: "ble_olo", region: "Olofström", regionId: "ble" },
      { id: "ble_ron", region: "Ronneby", regionId: "ble" },
      { id: "ble_sol", region: "Sölvesborg", regionId: "ble" },
    ],
  },
  {
    id: "dal",
    country: "Dalarna",
    regions: [
      { id: "dal_ave", region: "Avesta", regionId: "dal" },
      { id: "dal_bor", region: "Borlänge", regionId: "dal" },
      { id: "dal_fal", region: "Falun", regionId: "dal" },
      { id: "dal_gag", region: "Gagnef", regionId: "dal" },
      { id: "dal_hed", region: "Hedemora", regionId: "dal" },
      { id: "dal_lek", region: "Leksand", regionId: "dal" },
      { id: "dal_lud", region: "Ludvika", regionId: "dal" },
      { id: "dal_mal", region: "Malung-Sälen", regionId: "dal" },
      { id: "dal_mor", region: "Mora", regionId: "dal" },
      { id: "dal_ors", region: "Orsa", regionId: "dal" },
      { id: "dal_rat", region: "Rättvik", regionId: "dal" },
      { id: "dal_sme", region: "Smedjebacken", regionId: "dal" },
      { id: "dal_sat", region: "Säter", regionId: "dal" },
      { id: "dal_van", region: "Vansabro", regionId: "dal" },
      { id: "dal_alv", region: "Älvdalen", regionId: "dal" },
    ],
  },
  {
    id: "got",
    country: "Gotland",
    regions: [{ id: "got_got", region: "Gotland", regionId: "got" }],
  },
  {
    id: "gav",
    country: "Gävleborg",
    regions: [
      { id: "gav_bol", region: "Bollnäs", regionId: "gav" },
      { id: "gav_gav", region: "Gävle", regionId: "gav" },
      { id: "gav_hof", region: "Hofors", regionId: "gav" },
      { id: "gav_hud", region: "Hudiksvall", regionId: "gav" },
      { id: "gav_lju", region: "Ljusdal", regionId: "gav" },
      { id: "gav_nor", region: "Nordanstig", regionId: "gav" },
      { id: "gav_ock", region: "Ockelbo", regionId: "gav" },
      { id: "gav_ova", region: "Ovanåker", regionId: "gav" },
      { id: "gav_san", region: "Sandviken", regionId: "gav" },
      { id: "gav_sod", region: "Söderhamn", regionId: "gav" },
    ],
  },
  {
    id: "hal",
    country: "Halland",
    regions: [
      { id: "hal_fal", region: "Falkenberg", regionId: "hal" },
      { id: "hal_hal", region: "Halmstad", regionId: "hal" },
      { id: "hal_hyl", region: "Hylte", regionId: "hal" },
      { id: "hal_kun", region: "Kungsbacka", regionId: "hal" },
      { id: "hal_var", region: "Varberg", regionId: "hal" },
      { id: "hal_lah", region: "Laholm", regionId: "hal" },
    ],
  },
  {
    id: "jam",
    country: "Jämtland",
    regions: [
      { id: "jam_ber", region: "Berg", regionId: "jam" },
      { id: "jam_bra", region: "Bräcke", regionId: "jam" },
      { id: "jam_har", region: "Härjedalen", regionId: "jam" },
      { id: "jam_kro", region: "Krokom", regionId: "jam" },
      { id: "jam_rag", region: "Ragunda", regionId: "jam" },
      { id: "jam_str", region: "Strömsund", regionId: "jam" },
      { id: "jam_are", region: "Åre", regionId: "jam" },
      { id: "jam_ost", region: "Östersund", regionId: "jam" },
    ],
  },
  {
    id: "jon",
    country: "Jönköping",
    regions: [
      { id: "jon_ane", region: "Aneby", regionId: "jon" },
      { id: "jon_eks", region: "Eksjö", regionId: "jon" },
      { id: "jon_gis", region: "Gislaved", regionId: "jon" },
      { id: "jon_gno", region: "Gnosjö", regionId: "jon" },
      { id: "jon_hab", region: "Habo", regionId: "jon" },
      { id: "jon_jon", region: "Jönköping", regionId: "jon" },
      { id: "jon_mul", region: "Mullsjö", regionId: "jon" },
      { id: "jon_nas", region: "Nässjö", regionId: "jon" },
      { id: "jon_sav", region: "Sävsjö", regionId: "jon" },
      { id: "jon_tra", region: "Tranås", regionId: "jon" },
      { id: "jon_vag", region: "Vaggeryd", regionId: "jon" },
      { id: "jon_vet", region: "Vetlanda", regionId: "jon" },
      { id: "jon_var", region: "Värnamo", regionId: "jon" },
    ],
  },
  {
    id: "kal",
    country: "Kalmar",
    regions: [
      { id: "kal_bor", region: "Borgholm" },
      { id: "kal_emm", region: "Emmaboda" },
      { id: "kal_hul", region: "Hultsfred" },
      { id: "kal_hog", region: "Högsby" },
      { id: "kal_kal", region: "Kalmar" },
      { id: "kal_mon", region: "Mönsterås" },
      { id: "kal_mor", region: "Mörbylånga" },
      { id: "kal_nyb", region: "Nybro" },
      { id: "kal_osk", region: "Oskarshamn" },
      { id: "kal_tor", region: "Torsås" },
      { id: "kal_vim", region: "Vimmerby" },
      { id: "kal_vas", region: "Västervik" },
    ],
  },
  {
    id: "kro",
    country: "Kronoberg",
    regions: [
      { id: "kro_alv", region: "Alvesta" },
      { id: "kro_les", region: "Lessebo" },
      { id: "kro_lju", region: "Ljungby" },
      { id: "kro_mar", region: "Markaryd" },
      { id: "kro_tin", region: "Tingsryd" },
      { id: "kro_upp", region: "Uppvidinge" },
      { id: "kro_vax", region: "Växjö" },
      { id: "kro_alm", region: "Älmhult" },
    ],
  },
  {
    id: "ska",
    country: "Skåne",
    regions: [
      { id: "ska_bju", region: "Bjuv" },
      { id: "ska_bro", region: "Bromölla" },
      { id: "ska_bur", region: "Burlöv" },
      { id: "ska_bas", region: "Båstad" },
      { id: "ska_esl", region: "Eslöv" },
      { id: "ska_hel", region: "Helsingborg" },
      { id: "ska_has", region: "Hässleholm" },
      { id: "ska_hog", region: "Höganäs" },
      { id: "ska_hor", region: "Hörby" },
      { id: "ska_hoo", region: "Höör" },
      { id: "ska_kli", region: "Klippan" },
      { id: "ska_kri", region: "Kristianstad" },
      { id: "ska_kav", region: "Kävlinge" },
      { id: "ska_lan", region: "Landskrona" },
      { id: "ska_lom", region: "Lomma" },
      { id: "ska_lun", region: "Lund" },
      { id: "ska_mal", region: "Malmö" },
      { id: "ska_osb", region: "Osby" },
      { id: "ska_per", region: "Perstorp" },
      { id: "ska_sim", region: "Simrishamn" },
      { id: "ska_sjo", region: "Sjöbo" },
      { id: "ska_sku", region: "Skurup" },
      { id: "ska_sta", region: "Staffanstorp" },
      { id: "ska_sva", region: "Svalöv" },
      { id: "ska_sve", region: "Svedala" },
      { id: "ska_tom", region: "Tomelilla" },
      { id: "ska_tre", region: "Trelleborg" },
      { id: "ska_vel", region: "Vellinge" },
      { id: "ska_yst", region: "Ystad" },
      { id: "ska_ast", region: "Åstorp" },
      { id: "ska_ost", region: "Östra Göinge" },
      { id: "ska_ang", region: "Ängelholm" },
      { id: "ska_ork", region: "Örkelljunga" },
    ],
  },
  {
    id: "sto",
    country: "Stockholm",
    regions: [
      { id: "sto_bot", region: "Botkyrka" },
      { id: "sto_dan", region: "Danderyd" },
      { id: "sto_eke", region: "Ekerö" },
      { id: "sto_han", region: "Haninge" },
      { id: "sto_hud", region: "Huddinge" },
      { id: "sto_jar", region: "Järfälla" },
      { id: "sto_lid", region: "Lidingö" },
      { id: "sto_nac", region: "Nacka" },
      { id: "sto_nor", region: "Norrtälje" },
      { id: "sto_nyk", region: "Nykvarn" },
      { id: "sto_nyn", region: "Nynäshamn" },
      { id: "sto_sal", region: "Salem" },
      { id: "sto_sig", region: "Sigtuna" },
      { id: "sto_sol", region: "Sollentuna" },
      { id: "sto_son", region: "Solna" },
      { id: "sto_sto", region: "Stockholm" },
      { id: "sto_sun", region: "Sundbyberg" },
      { id: "sto_sod", region: "Södertälje" },
      { id: "sto_tyr", region: "Tyresö" },
      { id: "sto_tab", region: "Täby" },
      { id: "sto_upp", region: "Upplands Väsby" },
      { id: "sto_vas", region: "Väsby" },
      { id: "sto_upb", region: "Upplands-Bro" },
      { id: "sto_val", region: "Vallentuna" },
      { id: "sto_vax", region: "Vaxholm" },
      { id: "sto_var", region: "Värmdö" },
      { id: "sto_ost", region: "Österåker" },
    ],
  },
  {
    id: "sod",
    country: "Södermanland",
    regions: [
      { id: "sod_esk", region: "Eskilstuna" },
      { id: "sod_fle", region: "Flen" },
      { id: "sod_gne", region: "Gnesta" },
      { id: "sod_kat", region: "Katrineholm" },
      { id: "sod_nyk", region: "Nyköping" },
      { id: "sod_oxe", region: "Oxelösund" },
      { id: "sod_str", region: "Strängnäs" },
      { id: "sod_tro", region: "Trosa" },
      { id: "sod_vin", region: "Vingåker" },
    ],
  },
  {
    id: "upp",
    country: "Uppsala",
    regions: [
      { id: "upp_enk", region: "Enköping" },
      { id: "upp_heb", region: "Heby" },
      { id: "upp_hab", region: "Håbo" },
      { id: "upp_kni", region: "Knivsta" },
      { id: "upp_tie", region: "Tierp" },
      { id: "upp_upp", region: "Uppsala" },
      { id: "upp_alv", region: "Älvkarleby" },
      { id: "upp_ost", region: "Östhammar" },
    ],
  },
  {
    id: "var",
    country: "Värmland",
    regions: [
      { id: "var_arv", region: "Arvika" },
      { id: "var_eda", region: "Eda" },
      { id: "var_fil", region: "Filipstad" },
      { id: "var_for", region: "Forshaga" },
      { id: "var_gru", region: "Grums" },
      { id: "var_hag", region: "Hagfors" },
      { id: "var_ham", region: "Hammarö" },
      { id: "var_kar", region: "Karlstad" },
      { id: "var_kil", region: "Kil" },
      { id: "var_kri", region: "Kristinehamn" },
      { id: "var_mun", region: "Munkfors" },
      { id: "var_sto", region: "Storfors" },
      { id: "var_sun", region: "Sunne" },
      { id: "var_saf", region: "Säffle" },
      { id: "var_tor", region: "Torsby" },
      { id: "var_arj", region: "Årjäng" },
    ],
  },
  {
    id: "vab",
    country: "Västerbotten",
    regions: [
      { id: "vab_bju", region: "Bjurholm" },
      { id: "vab_dor", region: "Dorotea" },
      { id: "vab_lyc", region: "Lycksele" },
      { id: "vab_mal", region: "Malå" },
      { id: "vab_nor", region: "Nordmaling" },
      { id: "vab_nos", region: "Norsjö" },
      { id: "vab_rob", region: "Robertsfors" },
      { id: "vab_ske", region: "Skellefteå" },
      { id: "vab_sor", region: "Sorsele" },
      { id: "vab_sto", region: "Storuman" },
      { id: "vab_ume", region: "Umeå" },
      { id: "vab_vil", region: "Vilhelmina" },
      { id: "vab_vin", region: "Vindeln" },
      { id: "vab_van", region: "Vännäs" },
      { id: "vab_ase", region: "Åsele" },
    ],
  },
  {
    id: "van",
    country: "Västernorrland",
    regions: [
      { id: "van_har", region: "Härnösand" },
      { id: "van_kra", region: "Kramfors" },
      { id: "van_sol", region: "Sollefteå" },
      { id: "van_sun", region: "Sundsvall" },
      { id: "van_tim", region: "Timrå" },
      { id: "van_ang", region: "Ånge" },
      { id: "van_orn", region: "Örnsköldsvik" },
    ],
  },
  {
    id: "vam",
    country: "Västmanland",
    regions: [
      { id: "vam_arb", region: "Arboga" },
      { id: "vam_fag", region: "Fagersta" },
      { id: "vam_hal", region: "Hallstahammar" },
      { id: "vam_kun", region: "Kungsör" },
      { id: "vam_kop", region: "Köping" },
      { id: "vam_nor", region: "Norberg" },
      { id: "vam_sal", region: "Sala" },
      { id: "vam_ski", region: "Skinnskatteberg" },
      { id: "vam_sur", region: "Surahammar" },
      { id: "vam_vas", region: "Västerås" },
    ],
  },
  {
    id: "vag",
    country: "Västra Götaland",
    regions: [
      { id: "vag_ale", region: "Ale" },
      { id: "vag_ali", region: "Alingsås" },
      { id: "vag_ben", region: "Bengtsfors" },
      { id: "vag_bol", region: "Bollebygd" },
      { id: "vag_bor", region: "Borås" },
      { id: "vag_dal", region: "Dals-Ed" },
      { id: "vag_ess", region: "Essunga" },
      { id: "vag_fal", region: "Falköping" },
      { id: "vag_far", region: "Färgelanda" },
      { id: "vag_gra", region: "Grästorp" },
      { id: "vag_gul", region: "Gullspång" },
      { id: "vag_got", region: "Göteborg" },
      { id: "vag_goe", region: "Götene" },
      { id: "vag_her", region: "Herrljunga" },
      { id: "vag_hjo", region: "Hjo" },
      { id: "vag_har", region: "Härryda" },
      { id: "vag_kar", region: "Karlsborg" },
      { id: "vag_kun", region: "Kungälv" },
      { id: "vag_ler", region: "Lerum" },
      { id: "vag_lid", region: "Lidköping" },
      { id: "vag_lil", region: "Lilla Edet" },
      { id: "vag_lys", region: "Lysekil" },
      { id: "vag_mar", region: "Mariestad" },
      { id: "vag_mak", region: "Mark" },
      { id: "vag_mel", region: "Mellerud" },
      { id: "vag_mun", region: "Munkedal" },
      { id: "vag_mol", region: "Mölndal" },
      { id: "vag_oru", region: "Orust" },
      { id: "vag_par", region: "Partille" },
      { id: "vag_ska", region: "Skara" },
      { id: "vag_sko", region: "Skövde" },
      { id: "vag_sot", region: "Sotenäs" },
      { id: "vag_ste", region: "Stenungsund" },
      { id: "vag_str", region: "Strömstad" },
      { id: "vag_sve", region: "Svenljunga" },
      { id: "vag_tan", region: "Tanum" },
      { id: "vag_tib", region: "Tibro" },
      { id: "vag_tid", region: "Tidaholm" },
      { id: "vag_tjo", region: "Tjörn" },
      { id: "vag_tra", region: "Tranemo" },
      { id: "vag_tro", region: "Trollhättan" },
      { id: "vag_tor", region: "Töreboda" },
      { id: "vag_udd", region: "Uddevalla" },
      { id: "vag_ulr", region: "Ulricehamn" },
      { id: "vag_var", region: "Vara" },
      { id: "vag_vag", region: "Vårgårda" },
      { id: "vag_van", region: "Vänersborg" },
      { id: "vag_ama", region: "Åmål" },
      { id: "vag_ock", region: "Öckerö" },
    ],
  },
  {
    id: "ore",
    country: "Örebro",
    regions: [
      { id: "ore_ask", region: "Askersund" },
      { id: "ore_deg", region: "Degerfors" },
      { id: "ore_hal", region: "Hallsberg" },
      { id: "ore_hae", region: "Hällefors" },
      { id: "ore_kar", region: "Karlskoga" },
      { id: "ore_kum", region: "Kumla" },
      { id: "ore_lax", region: "Laxå" },
      { id: "ore_lek", region: "Lekeberg" },
      { id: "ore_lin", region: "Lindesberg" },
      { id: "ore_nor", region: "Nora" },
      { id: "ore_ore", region: "Örebro" },
      { id: "ore_lju", region: "Ljusnarsberg" },
    ],
  },
  {
    id: "ost",
    country: "Östergötland",
    regions: [
      { id: "ost_box", region: "Boxholm" },
      { id: "ost_fin", region: "Finspång" },
      { id: "ost_kin", region: "Kinda" },
      { id: "ost_lin", region: "Linköping" },
      { id: "ost_mjo", region: "Mjölby" },
      { id: "ost_mot", region: "Motala" },
      { id: "ost_nor", region: "Norrköping" },
      { id: "ost_sod", region: "Söderköping" },
      { id: "ost_vad", region: "Vadstena" },
      { id: "ost_val", region: "Valdemarsvik" },
      { id: "ost_ydr", region: "Ydre" },
      { id: "ost_atv", region: "Åtvidaberg" },
      { id: "ost_ode", region: "Ödeshög" },
    ],
  },
];
